---

- hosts: klio
  sudo: true
  gather_facts: true

  vars:

  roles:
    - common
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: true
        }
      }

