---

- hosts: mneme
  sudo: true
  gather_facts: true

  vars:

  roles:
    - loechel.ansible_role.base
    - { role: loechel.ansible_role.maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: true
        }
      }
    - loechel.ansible_role.trac
    - loechel.ansible_role.redmine
    - loechel.ansible_role.gitlab
